version: '3.4'
services:
  manager:
    build:
      context: .
      dockerfile: docker/manager.Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - broker

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    deploy:
       mode: replicated
       replicas: 3
    env_file: .env
    depends_on:
      - broker

  broker:
    image: "redis:7.2-alpine"
    env_file: .env
    ports:
      #TODO: left for debugging from outside of the network
      - "6379:6379"
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
      - broker:/data
    command:
      - /bin/sh
      - -c
      - |
        redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}" 
        --port "$${REDIS_PORT:?REDIS_PORT variable is not set}" 
        /usr/local/etc/redis/redis.conf"

volumes:
  broker:

networks:
  app-network:
    driver: bridge
